export const FILE_ICON_CLASS_MAP: Record<string, string> = {
  'pdf': 'fas fa-file-pdf text-red-500',
  'doc': 'fas fa-file-word text-blue-600',
  'docx': 'fas fa-file-word text-blue-600',
  'odt': 'fas fa-file-word text-blue-400',
  'xls': 'fas fa-file-excel text-green-600',
  'xlsx': 'fas fa-file-excel text-green-600',
  'csv': 'fas fa-file-csv text-green-500',
  'ppt': 'fas fa-file-powerpoint text-orange-500',
  'pptx': 'fas fa-file-powerpoint text-orange-500',
  'jpg': 'fas fa-file-image text-blue-500',
  'jpeg': 'fas fa-file-image text-blue-500',
  'png': 'fas fa-file-image text-blue-400',
  'gif': 'fas fa-file-image text-pink-400',
  'svg': 'fas fa-file-image text-purple-500',
  'txt': 'fas fa-file-alt text-gray-500',
  'md': 'fas fa-file-alt text-gray-500',
  'json': 'fas fa-file-code text-yellow-500',
  'xml': 'fas fa-file-code text-yellow-600',
  'html': 'fas fa-file-code text-orange-600',
  'css': 'fas fa-file-code text-blue-400',
  'js': 'fas fa-file-code text-yellow-400',
  'ts': 'fas fa-file-code text-blue-500',
  'zip': 'fas fa-file-archive text-yellow-700',
  'rar': 'fas fa-file-archive text-yellow-700',
  '7z': 'fas fa-file-archive text-yellow-700',
  'mp4': 'fas fa-file-video text-purple-500',
  'avi': 'fas fa-file-video text-purple-500',
  'mov': 'fas fa-file-video text-purple-500',
  'wmv': 'fas fa-file-video text-purple-500',
  'mkv': 'fas fa-file-video text-purple-500',
  'mp3': 'fas fa-file-audio text-indigo-500',
  'wav': 'fas fa-file-audio text-indigo-500',
  'flac': 'fas fa-file-audio text-indigo-500',
  'exe': 'fas fa-cog text-gray-700',
  'apk': 'fas fa-mobile-alt text-green-600',
  'iso': 'fas fa-dot-circle text-gray-600',
  'default': 'fas fa-file text-gray-400'
};

export const FILE_BG_CLASS_MAP: Record<string, string> = {
  'pdf': 'bg-red-100',
  'doc': 'bg-blue-100',
  'docx': 'bg-blue-100',
  'odt': 'bg-blue-50',
  'xls': 'bg-green-100',
  'xlsx': 'bg-green-100',
  'csv': 'bg-green-50',
  'ppt': 'bg-orange-100',
  'pptx': 'bg-orange-100',
  'jpg': 'bg-blue-50',
  'jpeg': 'bg-blue-50',
  'png': 'bg-blue-100',
  'gif': 'bg-pink-100',
  'svg': 'bg-purple-100',
  'txt': 'bg-gray-100',
  'md': 'bg-gray-100',
  'json': 'bg-yellow-100',
  'xml': 'bg-yellow-100',
  'html': 'bg-orange-100',
  'css': 'bg-blue-100',
  'js': 'bg-yellow-50',
  'ts': 'bg-blue-50',
  'zip': 'bg-yellow-50',
  'rar': 'bg-yellow-50',
  '7z': 'bg-yellow-50',
  'mp4': 'bg-purple-50',
  'avi': 'bg-purple-50',
  'mov': 'bg-purple-50',
  'wmv': 'bg-purple-50',
  'mkv': 'bg-purple-50',
  'mp3': 'bg-indigo-100',
  'wav': 'bg-indigo-100',
  'flac': 'bg-indigo-100',
  'exe': 'bg-gray-200',
  'apk': 'bg-green-50',
  'iso': 'bg-gray-50',
  'default': 'bg-gray-50'
};
